<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Cláusula Informativa Del Tratamiento De Datos Personales</h1>
    <p>"En cumplimiento de lo dispuesto por la Ley Nº 29733, Ley de Protección de Datos Personales (en adelante LPDP) y su reglamento aprobado por Decreto Supremo Nº 003-2013-JUS, el Seguro Social de Salud-ESSALUD, desea poner en conocimiento de sus interesados, los siguientes aspectos relacionados con sus datos personales:</p>
    <p>1. TITULAR DEL BANCO DE DATOS PERSONALES: El titular del presente banco de datos en el que se almacenarán los datos personales facilitados en el presente Formulario/Formato//Contrato/Plataforma en Línea/VIVA, es el Seguro Social de Salud-ESSALUD, con dirección legal en Jirón Domingo Cueto N° 120, Jesús María, Lima.
    La existencia de este banco de datos personales ha sido declarada a la Autoridad Nacional de Protección de Datos Personales, mediante su inscripción en el Registro Nacional de Protección de Datos Personales, con la denominación de “ASEGURADOS”, con el código de registro: RNPDP Nº RESOLUCION N.º 2793-2021-JUS/DGTAIPD-DPDP, del cual es Responsable la Gerencia Central de Seguros y Prestaciones Económicas de ESSALUD.
    Se informa al titular de datos personales que, cualquier tratamiento de datos personales, se ajusta a lo establecido por la legislación vigente en PERÚ en la materia (Ley N° 29733 y su reglamento).</p>
    <p>2. FINALIDAD: El Seguro Social de Salud-ESSALUD, tratará los datos personales del asegurado titular y sus derechohabientes, con la finalidad de: Recopilar información de los asegurados para brindarles prestaciones de salud, económicas y sociales, verificar su cobertura de seguros, efectuar los controles para el proceso de atención e informar a las entidades de supervisión del sector salud. Siendo utilizados con propósitos limitados, tal como los expuestos precedentemente.</p>
    <p>3. TRANSFERENCIAS Y DESTINATARIOS: Los datos personales se transferirán a nivel nacional a: Entidades Prestadoras de Salud (EPS), Asociaciones Administradoras de Fondo de Pensiones (AFP), Oficina de Normalización Previsional (ONP), Superintendencia Nacional de Salud (SUSALUD), programas sociales, Superintendencia Nacional de Aduanas y Administración Tributaria, consorcios aseguradores del +Salud Seguro de Accidentes, otras entidades públicas con las que se haya suscrito convenios de colaboración interinstitucional e intercambio prestacional.</p>
    <p>4. PLAZO DURANTE EL CUAL SE CONSERVARÁN LOS DATOS PERSONALES: Los datos personales proporcionados se conservarán en tanto sea necesario para los servicios detallados en el numeral 2 del presente documento.</p>
    <p>5.	EJERCICIO DE LOS DERECHOS DE INFORMACIÓN (ACCESO, RECTIFICACIÓN, CANCELACIÓN Y OPOSICIÓN DE LOS DATOS): Como titular de sus datos personales el interesado tiene el derecho de acceder a sus datos en posesión del Seguro Social de Salud, conocer las características de su tratamiento, rectificarlos en caso de ser inexactos o incompletos; solicitar sean suprimidos o cancelados al considerarlos innecesarios para las finalidades previamente expuestas o bien oponerse a su tratamiento para fines específicos.
        El usuario podrá en todo momento revocar el consentimiento otorgado expresamente, tanto como limitar el uso o divulgación de sus datos personales.
        El usuario podrá dirigir su solicitud de ejercicio de los derechos a la siguiente dirección: Jirón Domingo Cueto N° 120, Jesús maría – Lima, establecimiento de ESSALUD, o a la siguiente dirección de correo electrónico: Derechos.arco@essalud.gob.pe en los términos que establece el Reglamento de la Ley Nº 29733 y en concordancia con el formulario de ejercicio de derechos correspondiente.
        De considerar el usuario que no ha sido atendido en el ejercicio de sus derechos, puede presentar un reclamo ante la Autoridad Nacional de Protección de Datos Personales, dirigiéndose a la Mesa de Partes del Ministerio de Justicia y Derechos Humanos: Calle Scipión Llona 350, Miraflores, Lima, Perú o ingresando a la web: https://www.gob.pe/minjus
        El Seguro Social de Salud - ESSALUD será responsable del banco de datos personales denominado ASEGURADOS y de los datos personales contenidos en éste. Con el objeto de evitar la pérdida, mal uso, alteración, acceso no autorizado y robo de los datos personales o información confidencial facilitados por los usuarios y/o los clientes, ESSALUD adopta los niveles de seguridad y de protección de datos personales legalmente requeridos e instala todos los medios y medidas técnicas a su alcance.</p>
</body>
</html>